development:
  adapter: mysql2
  encoding: utf8
  database: events
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  database: events_production
  username: root
  password: 
